"ui.text" = { fg = "#c3c3c3"}
"ui.selection" = { fg = "white", bg = "#4f46e5" }
"ui.cursor" = { fg = "black", bg = "#ff0068" }
"ui.cursor.primary" = { fg = "black", bg = "#ff0068" }
"ui.cursor.match" = { fg = "black", bg = "#00ff00" }
"ui.statusline.separator" = "#00ff00"
"ui.background.separator" = "#222222"
"ui.window" = "#444444"
"ui.linenr" = "gray"
"ui.linenr.selected" = { fg = "white", bg = "gray" }
"ui.statusline" = { bg = "#222222", fg = "green" }
"ui.statusline.inactive" = { bg = "#070707", fg = "white" }
"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { bg = "light-gray", fg = "black" }
"ui.popup" = { fg = "white", bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.virtual.ruler" = { underline = { style = "line"} }

"keyword"     = { fg = "#f0f0f0" }
"string"      = { fg = "yellow_" }
"comment"     = { fg = "green_" }
"punctuation" = { fg = "teal_" }
"operator"    = { fg = "teal_" }
"function"    = { fg = "teal_bright_" }
"constant"    = { fg = "magenta_" }

"keyword.directive" = { fg = "violet_" }
"function.special"  = { fg = "violet_" }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "gray"

"warning" = { fg = "light-yellow" }
"error" = { fg = "light-red" }
"hint" = { fg = "light-blue" }

"diagnostic.warning" = { modifiers = ["underlined"] }
"diagnostic.error" = { modifiers = ["underlined"] }
"diagnostic.hint" = { modifiers = ["underlined"] }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }


[palette]
teal_ = "#0e9e8e"
teal_bright_ = "#26e1e6"
yellow_ = "#c6d441"
magenta_ = "#d811de"
red_ = "#E00000"
green_ = "#00d700"
violet_ = "#5f5fd7"
